# frozen_string_literal: true

begin
    require '/etc/one-appliance/lib/helpers'
rescue LoadError
    require_relative '../lib/helpers'
end

require 'socket'
require 'open3'
require 'rbconfig'
require 'fileutils'
require 'base64'
require_relative 'config'

# Base module for OpenNebula services
module Service

    # SlurmController service implmentation
    module SlurmController

        extend self

        def with_retries(attempts: 10, delay: 15, msg: 'Retrying operation...')
            attempts.times do |i|
                begin
                    return yield
                rescue StandardError => e
                    if i + 1 < attempts
                        msg(:warn, "#{msg} (#{i + 1}/#{attempts}). Error: #{e.message}. Retrying in #{delay}s.")
                        sleep delay
                    else
                        msg(:error, "Operation failed after #{attempts} attempts.")
                        raise e
                    end
                end
            end
        end

        DEPENDS_ON    = []

        def install
            msg :info, 'SlurmController::install'

            # Install dependencies
            bash 'apt update && apt install munge libmunge-dev slurmctld slurm-client slurm-wlm-basic-plugins ldap-utils sssd sssd-ldap libnss-sss libpam-sss -y'

            # Create slurm.conf
            slurm_conf = <<~CONF
                ClusterName=one
                SlurmctldHost=slurm-one-controller
                AuthType=auth/munge
                ProctrackType=proctrack/cgroup
                SchedulerType=sched/backfill
                SelectType=select/cons_tres
                GresTypes=gpu
                TaskPlugin=task/cgroup,task/affinity

                SlurmUser=slurm
                StateSaveLocation=/var/spool/slurmctld
                SlurmdSpoolDir=/var/spool/slurmd

                SlurmctldPidFile=/var/run/slurm/slurmctld.pid
                SlurmdPidFile=/var/run/slurm/slurmd.pid

                SlurmctldParameters=enable_configless

                MaxNodeCount=100

                Nodeset=one Feature=one

                PartitionName=all  Nodes=ALL Default=yes
            CONF

            File.write('/etc/slurm/slurm.conf', slurm_conf)

            gres_conf = <<~CONF
                AutoDetect=nvidia
            CONF
            File.write('/etc/slurm/gres.conf', gres_conf)

            cgroup_conf = <<~CONF
                CgroupAutomount=yes
                ConstrainDevices=yes
            CONF
            File.write('/etc/slurm/cgroup.conf', cgroup_conf)

            # Create directories and set permissions
            FileUtils.mkdir_p('/var/spool/slurmd')
            FileUtils.mkdir_p('/var/spool/slurmctld')
            FileUtils.chown_R('slurm', 'slurm', '/var/spool/slurmd')
            FileUtils.chown_R('slurm', 'slurm', '/var/spool/slurmctld')
            FileUtils.chmod(0700, '/var/spool/slurmd')
            FileUtils.chmod(0700, '/var/spool/slurmctld')

            # Enable service
            bash 'systemctl enable slurmctld'

            msg :info, 'Installation completed successfully'
        end

        def configure
            msg :info, 'SlurmController::configure'

            #
            # Hostname Management
            #
            desired_hostname = 'slurm-one-controller'
            current_hostname = Socket.gethostname.split('.').first

            if current_hostname != desired_hostname
                msg :info, "Hostname is '#{current_hostname}'," \
                          " changing to '#{desired_hostname}'"
                bash "hostnamectl set-hostname #{desired_hostname}"

                # Update /etc/hosts
                ip = controller_ipv4

                hosts_entry = "#{ip}\t#{desired_hostname}"

                unless File.read('/etc/hosts').include?(hosts_entry)
                    msg :info, "Adding '#{hosts_entry}' to /etc/hosts"
                    File.open('/etc/hosts', 'a') { |f| f.puts hosts_entry }
                end
            end

            #
            # Munge Key Management
            #
            munge_key_flag = '/etc/munge/one_key_generated'
            munge_key_path = '/etc/munge/munge.key'

            if !File.exist?(munge_key_flag)
                msg :info, 'Munge key not found or not generated by ONE,' \
                          ' creating a new one.'

                # Backup old key if it exists
                if File.exist?(munge_key_path)
                    timestamp   = Time.now.strftime('%Y%m%d%H%M%S')
                    backup_path = "/etc/munge/munge_old_#{timestamp}.key"
                    msg :info, "Backing up munge key to #{backup_path}"
                    FileUtils.mv(munge_key_path, backup_path)
                end

                # Generate new key, set owner, and create flag file
                bash "mungekey -c -k #{munge_key_path}"
                FileUtils.chown('munge', 'munge', munge_key_path)
                FileUtils.touch(munge_key_flag)

                # Enable and restart munge
                bash 'systemctl enable munge'
                bash 'systemctl restart munge'

                # Verify munge is working
                msg :info, 'Verifying munge service'
                bash 'munge -n | unmunge >/dev/null 2>&1'
                msg :info, 'Munge verification successful'

                # Expose the key to onegate with retries
                with_retries(msg: 'Attempting to update VM data in OneGate...') do
                    msg :info, 'Encoding munge key and updating OneGate'
                    key = Base64.strict_encode64(File.read(munge_key_path))
                    bash "onegate vm update --data MUNGE_KEY_BASE64=#{key}"
                end
                msg :info, 'Successfully updated OneGate with munge key'


                # Restart slurmctld and check
                msg :info, 'Restarting slurmctld'
                bash 'systemctl restart slurmctld'
                bash 'systemctl is-active slurmctld'
                msg :info, 'slurmctld started successfully'
            else
                msg :info, 'Munge key already generated by ONE,' \
                          ' ensuring services are running.'

                # Check if slurmctld is running, restart if not
                begin
                    bash 'systemctl is-active slurmctld'
                    msg :info, 'slurmctld is active.'
                rescue StandardError
                    msg :warn, 'slurmctld is not running,' \
                              ' attempting to restart.'
                    bash 'systemctl restart slurmctld'
                    bash 'systemctl is-active slurmctld'
                    msg :info, 'slurmctld started successfully'
                end
            end

            configure_ldap

            msg :info, 'Configuration completed successfully'
        end

        def ldap_simple_bind_enabled?
            !ONEAPP_LDAP_ADMIN_PASSWORD.empty?
        end

        def ldap_base_dn
            domain = ONEAPP_LDAP_DOMAIN.to_s.strip
            return '' if domain.empty?

            domain.include?('=') ? domain : domain.split('.').map { |p| "dc=#{p}" }.join(',')
        end

        def ldap_bind_dn
            name = ONEAPP_LDAP_BIND_USER.to_s.strip
            return '' if name.empty?

            name.include?('=') ? name : "cn=#{name},#{ldap_base_dn}"
        end

        def ldap_admin_dn
            name = ONEAPP_LDAP_ADMIN_USER.to_s.strip
            return '' if name.empty?

            name.include?('=') ? name : "cn=#{name},#{ldap_base_dn}"
        end

        def ldap_client_enabled?
            !ONEAPP_LDAP_ENABLE && !ONEAPP_LDAP_URL.to_s.empty? && !ONEAPP_LDAP_DOMAIN.to_s.empty?
        end

        def ldap_base_object_ldif
            attr, value = ldap_base_dn.split(',', 2).first.split('=', 2)
            attr = attr.downcase
            domain = ONEAPP_LDAP_DOMAIN.to_s.strip
            organization = if domain.empty?
                               'Slurm'
                           elsif domain.include?('=')
                               domain.split(',', 2).first.split('=', 2).last.capitalize
                           else
                               domain.split('.').first.capitalize
                           end

            case attr
            when 'dc'
                <<~LDIF
                    objectClass: dcObject
                    objectClass: organization
                    o: #{organization}
                    dc: #{value}
                LDIF
            when 'o'
                <<~LDIF
                    objectClass: organization
                    o: #{value}
                LDIF
            when 'ou'
                <<~LDIF
                    objectClass: organizationalUnit
                    ou: #{value}
                LDIF
            when 'c'
                <<~LDIF
                    objectClass: country
                    c: #{value}
                LDIF
            else
                <<~LDIF
                    objectClass: extensibleObject
                    #{attr}: #{value}
                LDIF
            end
        end

        def controller_ipv4
            Socket.ip_address_list
                  .find { |a| a.ipv4? && !a.ipv4_loopback? }
                  .ip_address
        end

        def publish_ldap_onegate
            ldap_url = "ldap://#{controller_ipv4}"
            with_retries(msg: 'Attempting to update OneGate with LDAP metadata...') do
                msg :info, 'Updating OneGate with LDAP connection metadata'
                bash "onegate vm update --data LDAP_URL=#{ldap_url}"
                bash "onegate vm update --data LDAP_DOMAIN=#{ONEAPP_LDAP_DOMAIN}"
                bash "onegate vm update --data LDAP_ADMIN_USER=#{ONEAPP_LDAP_ADMIN_USER}"
            end
            msg :info, 'Successfully updated OneGate with LDAP metadata'
        end

        def install_ldap_server
            FileUtils.mkdir_p('/etc/ldap')

            debconf = <<~DEBCONF
                slapd slapd/no_configuration boolean true
            DEBCONF
            debconf_file = '/etc/ldap/.one_slurm_ldap_debconf'
            file debconf_file, debconf, mode: 'u=rw,go=', overwrite: true

            bash <<~SCRIPT
                export DEBIAN_FRONTEND=noninteractive
                debconf-set-selections < #{debconf_file}
                apt update
                apt install slapd -y
                rm -f #{debconf_file}
            SCRIPT
        end

        def ensure_slapd_active
            bash 'systemctl enable slapd'
            bash 'systemctl restart slapd'
            bash 'systemctl is-active slapd'
        end

        def setup_ldap_database
            if File.exist?(LDAP_CONFIGURED_MARKER)
                msg :info, 'LDAP database already configured, ensuring slapd is active'
                return ensure_slapd_active
            end

            msg :info, 'Configuring OpenLDAP database'

            root_pw_line = ''
            if ldap_simple_bind_enabled?
                hash = bash("slappasswd -s #{ONEAPP_LDAP_ADMIN_PASSWORD}", chomp: true)
                root_pw_line = "olcRootPW: #{hash}\n"
            end

            database_ldif = <<~LDIF
                dn: olcDatabase=mdb,cn=config
                objectClass: olcDatabaseConfig
                objectClass: olcMdbConfig
                olcDatabase: mdb
                olcSuffix: #{ldap_base_dn}
                olcRootDN: #{ldap_admin_dn}
                #{root_pw_line}olcDbDirectory: /var/lib/ldap
                olcDbIndex: objectClass eq
                olcDbIndex: uid,cn eq
                olcDbIndex: uidNumber,gidNumber eq
                olcDbIndex: member,memberUid eq
                olcAccess: to attrs=userPassword by dn.exact="#{LDAP_EXTERNAL_ADMIN_DN}" manage by anonymous auth by * none
                olcAccess: to dn.subtree="ou=People,#{ldap_base_dn}" by dn.exact="#{LDAP_EXTERNAL_ADMIN_DN}" manage by dn.exact="#{ldap_admin_dn}" write by * read
                olcAccess: to dn.subtree="ou=Groups,#{ldap_base_dn}" by dn.exact="#{LDAP_EXTERNAL_ADMIN_DN}" manage by dn.exact="#{ldap_admin_dn}" write by * read
                olcAccess: to * by dn.exact="#{LDAP_EXTERNAL_ADMIN_DN}" manage by dn.exact="#{ldap_admin_dn}" write by * read
            LDIF

            base_ldif = <<~LDIF
                dn: #{ldap_base_dn}
                objectClass: top
                #{ldap_base_object_ldif}

                dn: ou=People,#{ldap_base_dn}
                objectClass: organizationalUnit
                ou: People

                dn: ou=Groups,#{ldap_base_dn}
                objectClass: organizationalUnit
                ou: Groups
            LDIF

            if ldap_simple_bind_enabled?
                verify_cmd = "ldapwhoami -x -D #{ldap_admin_dn} -w #{ONEAPP_LDAP_ADMIN_PASSWORD} >/dev/null"
            else
                verify_cmd = 'ldapwhoami -Y EXTERNAL -H ldapi:/// >/dev/null'
            end

            bootstrap_ldif_file = '/etc/ldap/.one_slurm_ldap_bootstrap.ldif'

            bash <<~SCRIPT
                install -d -o openldap -g openldap -m 0750 /etc/ldap/slapd.d
                if [ ! -f /etc/ldap/slapd.conf ]; then
                    printf 'CONFIGDBDIR\\t/etc/ldap/slapd.d\\n' > /etc/ldap/slapd.conf
                fi
                if [ ! -e /etc/ldap/slapd.d/cn=config.ldif ]; then
                    {
                        echo 'dn: cn=config'
                        echo 'objectClass: olcGlobal'
                        echo 'cn: config'
                        echo 'olcAllows: bind_v2'
                        echo ''
                        echo 'dn: olcDatabase={0}config,cn=config'
                        echo 'objectClass: olcDatabaseConfig'
                        echo 'objectClass: olcConfig'
                        echo 'olcDatabase: {0}config'
                        echo 'olcAccess: to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * none'
                        echo 'olcAccess: to attrs=userPassword,olcRootPW by anonymous auth by * none'
                        echo 'olcAccess: to * by * read'
                        echo 'olcLastMod: TRUE'
                        echo 'olcRootDN: cn=admin,cn=config'
                        echo ''
                        echo 'dn: cn=schema,cn=config'
                        echo 'objectClass: olcSchemaConfig'
                        echo 'cn: schema'
                        echo ''
                        echo 'include: file:///etc/ldap/schema/core.ldif'
                        echo 'include: file:///etc/ldap/schema/cosine.ldif'
                        echo 'include: file:///etc/ldap/schema/nis.ldif'
                        echo 'include: file:///etc/ldap/schema/inetorgperson.ldif'
                        echo ''
                        echo 'dn: cn=module{0},cn=config'
                        echo 'objectClass: olcModuleList'
                        echo 'cn: module{0}'
                        echo 'olcModulePath: /usr/lib/ldap'
                        echo 'olcModuleLoad: back_mdb.so'
                    } > #{bootstrap_ldif_file}
                    slapadd -n 0 -F /etc/ldap/slapd.d -l #{bootstrap_ldif_file}
                    chown -R openldap:openldap /etc/ldap/slapd.d
                    rm -f #{bootstrap_ldif_file}
                fi
            SCRIPT

            ensure_slapd_active

            bash <<~SCRIPT
                install -d -o openldap -g openldap -m 0700 /var/lib/ldap
                ldapadd -Y EXTERNAL -H ldapi:/// <<'LDIF'
                #{database_ldif}
                LDIF
                ldapadd -Y EXTERNAL -H ldapi:/// <<'LDIF'
                #{base_ldif}
                LDIF
                #{verify_cmd}
            SCRIPT

            FileUtils.touch(LDAP_CONFIGURED_MARKER)
            FileUtils.chmod(0o644, LDAP_CONFIGURED_MARKER)
            msg :info, 'OpenLDAP server configured successfully'
        end

        def configure_ldap
            if ONEAPP_LDAP_ENABLE
                unless ONEAPP_LDAP_URL.to_s.empty?
                    msg :info, 'ONEAPP_LDAP_ENABLE=YES; external LDAP URL inputs are ignored'
                end
                configure_local_ldap
            elsif ldap_client_enabled?
                stop_local_ldap
                configure_external_ldap_client
            else
                stop_local_ldap
                stop_sssd
            end
        end

        def configure_local_ldap
            msg :info, 'LDAP enabled, configuring controller local LDAP'
            install_ldap_server
            setup_ldap_database
            setup_ldap_client
            publish_ldap_onegate
        end

        def stop_local_ldap
            msg :info, 'Ensuring local slapd is stopped'
            bash 'systemctl disable --now slapd 2>/dev/null || true'
        end

        def stop_sssd
            msg :info, 'LDAP identity disabled, ensuring sssd is stopped'
            bash 'systemctl disable --now sssd 2>/dev/null || true'
        end

        def configure_external_ldap_client
            msg :info, 'Configuring controller external LDAP client'
            apply_sssd_ldap_client(ONEAPP_LDAP_URL)
            msg :info, 'SSSD external LDAP client configured successfully on controller'
        end

        def setup_ldap_client
            msg :info, 'Configuring SSSD LDAP client on controller'
            apply_sssd_ldap_client('ldap://127.0.0.1')
            msg :info, 'SSSD LDAP client configured successfully on controller'
        end

        def apply_sssd_ldap_client(ldap_uri)
            bind_lines = ''
            unless ldap_bind_dn.empty?
                bind_lines = <<~BIND
                    ldap_default_bind_dn = #{ldap_bind_dn}
                    ldap_default_authtok_type = password
                BIND
                bind_lines += "ldap_default_authtok = #{ONEAPP_LDAP_BIND_PASSWORD}\n" unless ONEAPP_LDAP_BIND_PASSWORD.empty?
            end

            sssd_conf = <<~SSSD
                [sssd]
                services = nss, pam
                config_file_version = 2
                domains = slurm

                [domain/slurm]
                id_provider = ldap
                auth_provider = ldap
                ldap_uri = #{ldap_uri}
                ldap_search_base = #{ldap_base_dn}
                ldap_user_search_base = ou=People,#{ldap_base_dn}
                ldap_group_search_base = ou=Groups,#{ldap_base_dn}
                cache_credentials = True
                enumerate = False
                #{bind_lines}ldap_id_use_start_tls = false
                ldap_tls_reqcert = never
            SSSD

            FileUtils.mkdir_p('/etc/sssd')
            File.write('/etc/sssd/sssd.conf', sssd_conf)
            FileUtils.chmod(0o600, '/etc/sssd/sssd.conf')

            ensure_nsswitch_sss

            bash <<~SCRIPT
                export DEBIAN_FRONTEND=noninteractive
                pam-auth-update --enable mkhomedir
            SCRIPT

            bash 'systemctl enable sssd'
            bash 'systemctl restart sssd'
            bash 'systemctl is-active sssd'
        end

        def ensure_nsswitch_sss
            nsswitch_path = '/etc/nsswitch.conf'
            lines = File.readlines(nsswitch_path)
            databases = %w[passwd group shadow]

            databases.each do |db|
                lines.map! do |line|
                    next line unless line =~ /^#{db}:/

                    fields = line.strip.split(/\s+/)
                    next line if fields.include?('sss')

                    "#{db}:\t#{fields[1..].join(' ')} sss\n"
                end
            end

            File.write(nsswitch_path, lines.join)
        end

        def bootstrap
            msg :info, 'SlurmController::bootstrap'
            # No bootstrap actions defined for the controller yet.
            msg :info, 'Bootstrap completed successfully'
        end

    end
end
