# frozen_string_literal: true

require 'base64'

# Munge key handling shared by both Slurm roles: the controller generates and
# publishes the key, the worker fetches and installs it.
module OneSlurm

    module Munge

        MUNGE_KEY_PATH = '/etc/munge/munge.key'
        MUNGE_KEY_FLAG = '/etc/munge/one_key_generated'

        def munge_key_generated?
            File.exist?(MUNGE_KEY_FLAG)
        end

        def munge_key_base64
            Base64.strict_encode64(File.read(MUNGE_KEY_PATH))
        end

        def generate_munge_key
            msg :info, 'Munge key not found or not generated by ONE,' \
                      ' creating a new one.'

            # Backup old key if it exists
            if File.exist?(MUNGE_KEY_PATH)
                timestamp   = Time.now.strftime('%Y%m%d%H%M%S')
                backup_path = "/etc/munge/munge_old_#{timestamp}.key"
                msg :info, "Backing up munge key to #{backup_path}"
                FileUtils.mv(MUNGE_KEY_PATH, backup_path)
            end

            # Generate new key, set owner, and create flag file
            bash "mungekey -c -k #{MUNGE_KEY_PATH}"
            FileUtils.chown('munge', 'munge', MUNGE_KEY_PATH)
            FileUtils.touch(MUNGE_KEY_FLAG)

            # Enable and restart munge
            bash 'systemctl enable munge'
            bash 'systemctl restart munge'

            # Verify munge is working
            msg :info, 'Verifying munge service'
            bash 'munge -n | unmunge >/dev/null 2>&1'
            msg :info, 'Munge verification successful'
        end

        def install_munge_key(munge_key_b64)
            # Decode and install the munge key from the controller
            msg(:info, 'Installing munge key from controller')
            munge_key = Base64.decode64(munge_key_b64)
            File.write(MUNGE_KEY_PATH, munge_key, mode: 'wb')
            FileUtils.chmod(0600, MUNGE_KEY_PATH)

            # Enable and restart the munge service
            bash('systemctl enable munge')
            bash('systemctl restart munge')
            msg(:info, 'Verifying munge service connectivity')
            bash('munge -n | unmunge >/dev/null 2>&1')
            msg(:info, 'Munge verification successful')
        end

    end

end
